name: symfony-demo-application
app_mount: disabled
home: ~
compose:
  - docker-compose.yml
proxy:
  caddy:
    - demo.lndo.site
  mailer:
    - mail.lndo.site:1080
services:
  php:
    meUser: app
  database:
    user: root
    working_dir: /
tooling:
  composer:
    service: php
    cmd: composer
    environment:
      XDEBUG_MODE: off
  console:
    service: php
    cmd: bin/console
  phpunit:
    service: php
    cmd: bin/phpunit
  php:
    service: php
    cmd: php
  psql:
    service: database
    cmd: psql -Uapp
