services:
  php:
    build:
      context: .
      target: dev
      dockerfile: docker/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=symfony"
      ENABLE_OPCACHE: 0
    volumes:
      - .:/app
    depends_on:
      - database
  caddy:
    build:
      context: .
      target: app_caddy
      dockerfile: docker/caddy/Dockerfile
    depends_on:
      - php
    environment:
      LANDO_WEBROOT: /app/public
      #MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      #MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/app/public
  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      LANDO_SERVICE_TYPE: psql
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: psql -U postgres -c "\\\l"
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]

volumes:
  caddy_data: ~
  caddy_config: ~
  db-data: ~
